# Generated by Django 4.1.1 on 2022-11-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Articulo',
        ),
    ]
